### ISSUE TITLE
MFRC522 stops reading cards after running for a long time

### ISSUE THREAD

**Issue by wesee-dev** [miguelbalboa/rfid#546] opened 2021-01-04 23:06 UTC
### Step 1: Describe your environment

 * OS version: Windows 10 Build 2004
 * Arduino IDE version: 1.8.10
 * MFRC522 Library version:  1.4.8 master branch
 * Arduino device: ESP32 WROOM
 * MFRC522 device: RC522
  
### Step 2: Describe the problem
The RC522 module stops reading cards after running for a long time, about two weeks.
After pressing the reset button of the ESP32 module, the module started reading cards again.
Is there a way to detect if module is unresponsive, or identify what caused this issue by reading a register in the RC522?
I think that periodically reset the mfrc522 could fix the problem, but I still have not tested this approach.

#### Affected file(s) or example(s):
  DumpInfo.ino
  
#### Steps to reproduce:

  1. Let the dumpInfo exemple running for a long period, in my case two weeks.
  2. Test if module is still reading cards.
  
#### Observed Results:

No cards were being read, no output in serial monitor when cards were aproximated.
The module started reading cards again when the ESP32 board was resetted.

I already took a look in the issues section but wasn't able to find any similiar issues, but I think this might be a common issue.

**Comment by Rotzbua** [comment] 2021-01-05 02:02
duplicate of #540

**Closed by Rotzbua** 2021-01-05 02:02 UTC
Labels: duplicate
